### ISSUE TITLE
[BUG] Issue list display

### ISSUE THREAD

**Issue by FBoucher** [gitkraken/gk-cli#123]
### Description

On Debian 12 with GK CLI 3.0.6
When doing the command `gk issue ls` the display is only correct if the text is super small.

![Image](https://github.com/user-attachments/assets/93d4d47e-3de7-4d60-9a57-4d4fd66e3158)

### GitKraken CLI Version

3.0.6

### OS Version

Debian 12

### Git Version

git version 2.39.5

**Comment by FBoucher** [comment]
phew! 😳
You got me worried it was my theme (and that I didn't think about validating that)

**Comment by JBUinfo** [comment]
Hi @FBoucher 
Can you check if the problem has been resolved [with the lastest version](https://github.com/gitkraken/gk-cli/releases/tag/v3.1.5)?

**Comment by JBUinfo** [comment]
Closing this assuming everything is resolved

**Comment by fboucher** [comment]
@JBUinfo I'm having trouble executing `gk`

```bach
gk   
Installing GitKraken core
failed opening source: open /tmp/gkinstall2069517082/gk_core_3.1.8_linux_386/gk: no such file or directory
```

**Comment by fboucher** [comment]
Look like there a new version!
I downloaded 3.1.9 
I don't have the error but the display is still broken
